# The URL the site will be built for
base_url = "/"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

theme = "ataraxia-zola"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

# When set to "true", emoji aliases translated to their corresponding
# Unicode emoji equivalent in the rendered Markdown files. (e.g.: :smile: => 😄)
render_emoji = true

default_language = "en"


[languages]
    [languages.en]
        title = "mxmtr's website"
        description = "About cloud native and stuff"
        generate_feed = true
        feed_filename = "atom.xml"
        taxonomies = [
            { name = "tags", feed = true, paginate_by = 5  },
            { name = "categories", feed = true, paginate_by = 5 }
        ]

# translations for the default language are not prefixed by languages.code
[translations]

post = "Post"
category = "Category"
tag = "Tag"
search = "Search"

404_message = "Page not found"

by = "By"
posted = "Posted"
updated = "Updated"
categories = "Categories"
tags = "Tags"
share = "Share"

next = "Next"
previous = "Previous"

short_copyright = "Some rights reserved."
full_copyright = """\
    Except where otherwise noted, the blog posts on this site are \
    licensed under the Creative Commons Attribution 4.0 International \
    (CC BY 4.0) License by the author.\
    """

[extra]
    author = "mxmtr"

    # Use a square image (same height as width)
    avatar = "images/avatar.jpg"

    # To use a favicon convert your image to https://realfavicongenerator.net/,
    # then download and copy the package to static/images/favicon
    favicon = true
    locale = "en_US"

    # Ataraxia uses Bootstrap icons,
    # you can go to https://icons.getbootstrap.com/ to find the full list
    [extra.menus]
        nav = [
            { name = "Home", url = "@/_index.md", icon = "bi-house" },
            { name = "Blog", url = "@/blog/_index.md", icon = "bi-file-earmark-text" },
            { name = "Source", url = "https://github.com/mxm-tr/personal-blog/", icon = "bi-github" },
        ]
    
    [extra.social]
        author_link = "/"
        links = [
            { name = "GitHub", url = "https://github.com/mxm-tr", icon = "bi-github" },
            { name = "LinkedIn", url = "https://linkedin.com/in/maximehubert/", icon = "bi-linkedin" },
            { name = "Polywork", url = "https://poly.me/maxime_hubert", icon = "bi-grid-3x3-gap" }
        ]

    [extra.comments]
        disqus = "user"

    [extra.copyright]
        name = "CC BY 4.0"
        url = "https://creativecommons.org/licenses/by/4.0/"
